name: Deploy on push to main

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} << 'EOF'
            cd /home/sites/baptiste-jullion.dev/muse
            git pull origin main
            docker build -t muse .
            docker stop muse-website || true
            docker rm muse-website || true
            docker run -d --name muse-website -p 42561:42561 muse
          EOF
